<?php

namespace Gesdon2Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonateurRepository extends EntityRepository
{
}
