index:
    path:     /index
    defaults: { _controller: Gesdon2Bundle:Default:index }

# page d'affichage de la liste des instances de l'entité passée en paramètre
list:
    path:     /list/{entity}
    defaults: { _controller: Gesdon2Bundle:Default:list }

# formulaire de création
new:
    path:     /new/{entity}
    defaults: { _controller: Gesdon2Bundle:Default:new }

# formulaire d'affichage
show:
    path:     /show/{entity}/{id}
    defaults: { _controller: Gesdon2Bundle:Default:show }

# formulaire de modification
edit:
    path:     /edit/{entity}/{id}
    defaults: { _controller: Gesdon2Bundle:Default:edit }

# formulaire de suppression
delete:
    path:     /delete/{entity}/{id}
    defaults: { _controller: Gesdon2Bundle:Default:delete }

# update
update:
    path:     /update/{entity}/{id}
    defaults: { _controller: Gesdon2Bundle:Default:update }