
gesdon2_index:
    path:     /index
    defaults: { _controller: Gesdon2Bundle:Default:index }

# page d'affichage de la liste des instances de l'entité passée en paramètre
gesdon2_homepage:
    path:     /liste/{nomEntite}
    defaults: { _controller: Gesdon2Bundle:Default:liste }

# formulaire de création de donateurs
gesdon2_ajouter:
    path:     /ajouter/{classe}
    defaults: { _controller: Gesdon2Bundle:Default:ajouter }

# page de notification entité créée
gesdon2_cree:
    path:     /cree/{nomEntite}
    defaults: {_controller: Gesdon2Bundle:Default:cree }

# CRUD Donateur
donateur:
   resource: "@Gesdon2Bundle/Controller/"
   type: annotation
   prefix: /

# CRUD Adresse
adresse:
  resource: "@Gesdon2Bundle/Controller/"
  type: annotation
  prefix: /

# CRUD Don
don:
   resource: "@Gesdon2Bundle/Controller/"
   type: annotation
   prefix: /