# Menu des entités modifiables.
index:
    path:     /index
    defaults: { _controller: Gesdon2Bundle:Default:index }


# page d'affichage de la liste des donateurs
donateur_list:
    path:     /Donateur
    defaults: { _controller: Gesdon2Bundle:Donateur:list }

# tableau des donateurs
donateur_table:
    path:     /Donateur/table
    defaults: { _controller: Gesdon2Bundle:Donateur:table }
    requirements:
        _method:    POST

# formulaire de création des donateurs
donateur_new:
    path:     /Donateur/new
    defaults: { _controller: Gesdon2Bundle:Donateur:new }

# formulaire de modification des donateurs
donateur_edit:
    path:     /Donateur/edit/{id}
    defaults: { _controller: Gesdon2Bundle:Donateur:edit }

# formulaire de suppression des donateurs
donateur_delete:
    path:     /Donateur/delete/{id}
    defaults: { _controller: Gesdon2Bundle:Donateur:delete }

# update
donateur_update:
    path:     /Donateur/update/{id}
    defaults: { _controller: Gesdon2Bundle:Donateur:update }


# page d'affichage de la liste des adresses
adresse_list:
    path:     /Adresse
    defaults: { _controller: Gesdon2Bundle:Adresse:list }

# formulaire de création des adresses
adresse_new:
    path:     /Adresse/new
    defaults: { _controller: Gesdon2Bundle:Adresse:new }

# formulaire de modification des adresses
adresse_edit:
    path:     /Adresse/edit/{id}
    defaults: { _controller: Gesdon2Bundle:Adresse:edit }

# formulaire de suppression des adresses
adresse_delete:
    path:     /Adresse/delete/{id}
    defaults: { _controller: Gesdon2Bundle:Adresse:delete }

# update
adresse_update:
    path:     /Adresse/update/{id}
    defaults: { _controller: Gesdon2Bundle:Adresse:update }

# page d'affichage de la liste des dons
don_list:
    path:     /Don
    defaults: { _controller: Gesdon2Bundle:Don:list }

# formulaire de création des dons
don_new:
    path:     /Don/new
    defaults: { _controller: Gesdon2Bundle:Don:new }

# formulaire de modification des dons
don_edit:
    path:     /Don/edit/{id}
    defaults: { _controller: Gesdon2Bundle:Don:edit }

# formulaire de suppression des dons
don_delete:
    path:     /Don/delete/{id}
    defaults: { _controller: Gesdon2Bundle:Don:delete }

# update
don_update:
    path:     /Don/update/{id}
    defaults: { _controller: Gesdon2Bundle:Don:update }
