services:
#    gesdon2.example:
#        class: Gesdon2Bundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

# extension pour conversion des objets en tableaux
# source : https://gist.github.com/ajaxray/7608395
    gesdon2.twig.to_array_extension:
        class: Gesdon2Bundle\Twig\ToArrayExtension
        tags:
            - { name: twig.extension }