services:
#    gesdon2.example:
#        class: Gesdon2Bundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

# extension pour conversion des objets en tableaux
# source : https://gist.github.com/ajaxray/7608395
    gesdon2.twig.to_array_extension:
        class: Gesdon2Bundle\Twig\ToArrayExtension
        tags:
            - { name: twig.extension }


# type de champ personnalisé AdresseSelector
    gesdon2.type.adresse_selector:
        class: Gesdon2Bundle\Form\AdresseSelectorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: adresse_selector }
# l'alias doit corresponde au nom renvoyé par la méthode getName() de la classe
# type de champ personnalisé DonateurSelector
    gesdon2.type.donateur_selector:
        class: Gesdon2Bundle\Form\DonateurSelectorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: donateur_selector }

# type de champ personnalisé DateRange
# source : https://gist.github.com/havvg/4204307
    gesdon2.type.date_range:
        class: Gesdon2Bundle\Form\DateRangeType
        tags:
            - { name: form.type, alias: date_range }


    gesdon2.repository.don:
        class: Gesdon2Bundle\Repository\DonRepository
        public: false
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Gesdon2Bundle:Don ]

    gesdon2.search.don:
        class: Gesdon2Bundle\Search\Don
        public: true
        arguments: ["@gesdon2.repository.don"]